services:
  app1:
    build:
      context: ./java-jenkins-demo
    image: java-demo
    container_name: java-demo
    ports:
      - "8081:8080"
    restart: always

  app2:
    build:
      context: ./java-jenkins-demo-2
    image: java-demo-2
    container_name: java-demo-2
    ports:
      - "8082:8080"
    restart: always

